In [3]:
import numpy as np

In [5]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [7]:
#Accessing element 4
a[0,3]

4

In [11]:
#Accessing element 13
a[1,5]

13

In [13]:
#Accessing row 1 only
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
#Accessing column 4 only
a[:,3]

array([ 4, 11])

In [19]:
#Performing slicing
a[0,1:6:2]

array([2, 4, 6])

In [23]:
#Performing slicing
a[1,2:-1:2]

array([10, 12])

In [29]:
#Changing particular element
a[0,5] = 78
print(a)

[[ 1  2  3  4  5 78  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
#Changing whole column
a[:,2] = [89,99]
print(a)

[[ 1  2 89  4  5 78  7]
 [ 8  9 99 11 12 13 14]]


In [41]:
#Changing element in a chain
a[0, 1:4:1] = [0]
print(a)

[[ 1  0  0  0  5 78  7]
 [ 8  9 99 11 12 13 14]]


In [43]:
#Working on 3D arrays
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
#Accessing element 3
b[0,1,0]

3

In [47]:
#Accessing element 6
b[1,0,1]

6