In [3]:
import numpy as np

In [9]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [11]:
# Generating an array of zeroes
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Generating an array of ones
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
# Generating an array of any number
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [17]:
# Generating an array of any number with shape of some other array
np.full(a.shape,77)

array([[77, 77, 77],
       [77, 77, 77]])

In [19]:
# Generating an array of random decimal numbers
np.random.rand(2,3,5)

array([[[0.13655852, 0.97410508, 0.52012923, 0.4962818 , 0.81987883],
        [0.30047612, 0.269803  , 0.91500218, 0.77516643, 0.88643685],
        [0.06723199, 0.13772434, 0.20464413, 0.2070373 , 0.33987111]],

       [[0.16989473, 0.22960723, 0.92060858, 0.41477811, 0.60358104],
        [0.57278264, 0.09509982, 0.65338438, 0.6992619 , 0.01439804],
        [0.1757004 , 0.32338206, 0.09857467, 0.51167684, 0.51792933]]])

In [21]:
# Generating an array of random decimal numbers with shape of some other array
np.random.random_sample(a.shape)

array([[0.07399342, 0.56418247, 0.81367345],
       [0.99561216, 0.09510805, 0.79226972]])

In [25]:
# Generating an array of random integers
np.random.randint(3,size=(3,3))

array([[2, 1, 1],
       [1, 1, 0],
       [0, 2, 0]])

In [43]:
# Generating an array of random integers with specified range
np.random.randint(-4,4,size=(2,2))

array([[-2,  3],
       [ 0,  2]])

In [47]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
# Repeat and array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [53]:
# Copying the arrays
a = np.array([1,23,4])
b = a.copy()
b[1] = 2
print(b)
print(a)

[1 2 4]
[ 1 23  4]
