In [13]:
import numpy as np

In [15]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [19]:
b = np.array([[5,4,6],[7,8,9]])
print(b)

[[5 4 6]
 [7 8 9]]


In [21]:
#Get Dimensions
a.ndim

1

In [23]:
b.ndim

2

In [25]:
a.shape

(3,)

In [27]:
b.shape

(2, 3)

In [29]:
a.dtype

dtype('int32')

In [31]:
b.dtype

dtype('int32')

In [33]:
a.itemsize

4

In [35]:
b.itemsize

4

In [37]:
a.size

3

In [39]:
b.size

6

In [41]:
a.nbytes

12

In [43]:
b.nbytes

24

In [45]:
a.size * a.itemsize

12

In [47]:
b.size * b.itemsize

24